# Generated by Django 3.2.6 on 2021-09-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('menor', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('cell', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True)),
                ('faixa', models.CharField(default='BRANCA', max_length=20)),
                ('data_inscricao', models.DateField(blank=True, verbose_name='Data de Inscrição')),
                ('horario', models.CharField(blank=True, max_length=20)),
                ('titulo', models.CharField(blank=True, default='', max_length=20)),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('taxa', models.FloatField()),
                ('inscritos', models.ManyToManyField(blank=True, to='main.Aluno')),
            ],
        ),
    ]
