# Generated by Django 3.2.6 on 2021-09-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_inscricao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
    ]
