# Generated by Django 3.2.6 on 2021-09-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210909_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='horario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
