# Generated by Django 3.2.6 on 2021-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210909_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='custo_operacao',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plano',
            name='nome',
            field=models.CharField(default='Plano sem nome', max_length=30),
        ),
        migrations.AlterField(
            model_name='plano',
            name='taxa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plano',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
