# Generated by Django 3.2.6 on 2021-09-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210910_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='inscritos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano_assinado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plano'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(default='', max_length=30),
        ),
    ]
