# Generated by Django 3.2.6 on 2021-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210911_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_busca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='faixa',
            field=models.CharField(max_length=20),
        ),
    ]
