# Generated by Django 3.2.6 on 2021-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210914_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='faixa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
