# Generated by Django 3.2.6 on 2021-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_aluno_faixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='faixa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
